Simplified logic and GCE support

diff --git a/root/usr/bin/run b/root/usr/bin/run
--- a/root/usr/bin/run
+++ b/root/usr/bin/run
@@ -1,5 +1,8 @@
 #!/bin/bash
 
+[ "${DEBUG}" == 1 ] && set -x
+unset DEBUG
+
 TIMESTAMP=$(date +%Y-%m-%d-%H%M%S)
 
 is_database()
@@ -20,9 +23,14 @@ send_to_aws()
    [ -n "${AWS_ACCESS_KEY_ID}" ] && \
    [ -n "${AWS_SECRET_ACCESS_KEY}" ] && \
    [ -n "${AWS_S3_BUCKET_NAME}" ] && \
-   [ -n "${AWS_REGION}" ]
+   [ -n "${AWS_REGION}" -o -n "${AWS_DEFAULT_REGION}" ]
 }
 
+send_to_gce()
+{
+   [ -n "${GOOGLE_APPLICATION_CREDENTIALS}" ] && \
+   [ -n "${GOOGLE_BUCKET_NAME}" ]
+}
 
 azure_upload()
 {
@@ -37,24 +45,37 @@ aws_upload()
     ${CONTAINER_SCRIPTS_PATH}/upload-aws "${1}"
 }
 
+gce_upload()
+{
+    echo "--> Uploading to GCE Bucket $GOOGLE_BUCKET_NAME/$1"
+    trap "rm -vf ${1}" EXIT
+    echo "--> Creating temporary file $1"
+    mkdir -p "${1%/*}"
+    cat > "${1}"
+    ${CONTAINER_SCRIPTS_PATH}/upload-gce "${1}"
+}
+
 
 upload()
 {
-    local prefix=${1//\//-}
-    local extension=${2:-}
-    local remote_path="${NAMESPACE}/${NAMESPACE_UID}/${prefix}-${TIMESTAMP}${extension}"
+    local namespace=${1}
+    local prefix=${2//\//-}
+    local extension=${3:-}
+    local namespace_uid=$(oc get namespaces/$namespace -o template --template='{{.metadata.uid}}')
+    local remote_path="${namespace,,}/${namespace_uid^^}/${prefix,,}-${TIMESTAMP^^}${extension,,}"
 
     if send_to_azure; then
         azure_upload "${remote_path}"
     elif send_to_aws; then
         aws_upload "${remote_path}"
+    elif send_to_gce; then
+        gce_upload "${remote_path}"
     fi
 }
 
-send_to_azure && is_azure=1 || is_azure=0
-send_to_aws && is_aws=1 || is_aws=0
+send_to_azure || send_to_aws || send_to_gce || has_valid_config=0 && has_valid_config=1
 
-if [ $(( $is_azure | $is_aws )) -eq 0 ]; then
+if [ $has_valid_config -ne 1 ]; then
     cat <<-EOF
 	ERROR: Please select one storage method by settings according env vars:
 	ERROR:
@@ -68,18 +89,14 @@ if [ $(( $is_azure | $is_aws )) -eq 0 ]; then
 	ERROR:      AWS_SECRET_ACCESS_KEY
 	ERROR:      AWS_S3_BUCKET_NAME
 	ERROR:      AWS_REGION or AWS_DEFAULT_REGION (optional)
+	ERROR:
+	ERROR:  - GCE Bucket
+	ERROR:      GOOGLE_APPLICATION_CREDENTIALS
+	ERROR:      GOOGLE_BUCKET_NAME
 	EOF
-    missconfig=1
+    exit 1
 fi
 
-if [ -z "${NAMESPACE}" ]; then
-    echo "ERROR: Missing env var NAMESPACE"
-    missconfig=1
-fi
-
-[ "${missconfig}" == 1 ] && exit 1
-[ "${DEBUG}" == 1 ] && set -x
-unset DEBUG
 
 # set up configuration for openshift client
 MASTER_URL=${MASTER_URL:-https://kubernetes.default.svc.cluster.local:443}
@@ -88,79 +105,63 @@ TOKEN_FILE=${TOKEN_FILE:-/var/run/secrets/kubernetes.io/serviceaccount/token}
 
 {
 # craft a kubeconfig, usually at $KUBECONFIG location
-oc config set-cluster master \
-    --certificate-authority="${MASTER_CA}" \
-    --server="${MASTER_URL}"
+[ -e "${MASTER_CA}" -a -e "${MASTER_URL}" ] &&
+    oc config set-cluster master \
+        --certificate-authority="${MASTER_CA}" \
+        --server="${MASTER_URL}" || true
 
-oc config set-credentials account \
-    --token="$(<${TOKEN_FILE})"
+[ -e "${TOKEN_FILE}" ] &&
+    oc config set-credentials account \
+        --token="$(<${TOKEN_FILE})" || true
 
-oc config set-context current \
-    --cluster=master \
-    --user=account \
-    --namespace="${NAMESPACE}"
-
-oc config use-context current
 } >/dev/null
 
-NAMESPACE_UID=`oc get namespaces/$NAMESPACE -o jsonpath --template='{.metadata.uid}'`
-
-resources=()
-
-dcs=$(oc get deploymentconfigs -o jsonpath \
-    --template='{.items[*].metadata.name}' \
-    -n ${NAMESPACE} \
-    ${LABEL_SELECTOR:+-l ${LABEL_SELECTOR}}
+resources=(
+    $(oc get deployments --all-namespaces -o template \
+        --template="{{range .items}}{{.metadata.namespace}}/{{.kind}}/{{.metadata.name}} {{end}}" \
+        ${LABEL_SELECTOR:+-l ${LABEL_SELECTOR}} || true)
+    $(oc get deploymentconfigs --all-namespaces -o template \
+        --template="{{range .items}}{{.metadata.namespace}}/{{.kind}}/{{.metadata.name}} {{end}}" \
+        ${LABEL_SELECTOR:+-l ${LABEL_SELECTOR}} || true)
+    $(oc get statefulsets --all-namespaces -o template \
+        --template="{{range .items}}{{.metadata.namespace}}/{{.kind}}/{{.metadata.name}} {{end}}" \
+        ${LABEL_SELECTOR:+-l ${LABEL_SELECTOR}} || true)
+    $(oc get petsets --all-namespaces -o template \
+        --template="{{range .items}}{{.metadata.namespace}}/{{.kind}}/{{.metadata.name}} {{end}}" \
+        ${LABEL_SELECTOR:+-l ${LABEL_SELECTOR}} || true)
+    $(oc get daemonset --all-namespaces -o template \
+        --template="{{range .items}}{{.metadata.namespace}}/{{.kind}}/{{.metadata.name}} {{end}}" \
+        ${LABEL_SELECTOR:+-l ${LABEL_SELECTOR}} || true)
 )
-
-for dc in ${dcs}; do
-    i=${#resources[*]}
-    resources[$i]=deploymentconfig/$dc
-done
-
-statefulsets=$(oc get statefulsets -o jsonpath \
-    --template='{.items[*].metadata.name}' \
-    -n ${NAMESPACE} \
-    ${LABEL_SELECTOR:+-l ${LABEL_SELECTOR}}
-)
-
-for ps in ${statefulsets}; do
-    i=${#resources[*]}
-    resources[$i]=pod/${ps}-0
-done
-
-petsets=$(oc get petset -o jsonpath \
-    --template='{.items[*].metadata.name}' \
-    -n ${NAMESPACE} \
-    ${LABEL_SELECTOR:+-l ${LABEL_SELECTOR}}
-)
-
-for ps in ${petsets}; do
-    i=${#resources[*]}
-    resources[$i]=pod/${ps}-0
-done
 
 if [ ${#resources[*]} -lt 1 ]; then
-    echo "--> No suitable applications to dump from '${NAMESPACE}'. Giving up..."
+    echo "--> No suitable applications to dump."
     exit 0
 fi
 
-echo "--> Found resouces: ${resources[*]}"
+echo  "--> Found ${#resources[*]} resources"
 
-for res in ${resources[*]}; do
-    if ! is_database ${NAMESPACE} ${res}; then
-        echo "--> Not a database: $NAMESPACE/${res}. Skipping..."
+for resource in ${resources[*]}; do
+    ns=${resource%%/*}
+    resource=${resource#*/}
+
+    if ! is_database ${ns} ${resource}; then
+        echo "--> Ignoring non-database $resource from namespace $ns"
         continue
     fi
 
-    echo "--> Dumping from $NAMESPACE/${res}"
+    echo "--> Dumping ${resource} from namespace $ns"
 
-    oc rsh -n ${NAMESPACE} ${res} <${CONTAINER_SCRIPTS_PATH}/dump-database | gzip -c - | pv --interval 5 --format '%b %t %r' | upload ${res} .gz
+    oc rsh -n ${ns} ${resource} <${CONTAINER_SCRIPTS_PATH}/dump-database |
+        gzip -c - |
+        pv --interval 5 --format '%b %t %r' |
+        upload $ns ${resource} .gz
+
     ret=$?
 
     if [ $ret -eq 1 ]; then
-        echo "ERROR: Fail generating backup: $res"
+        echo "ERROR: Fail generating backup for $resource from namespace $ns"
     elif [ $ret -eq 2 ]; then
-        echo "ERROR: Fail uploading backup: $res"
+        echo "ERROR: Fail uploading backup for $resource from namespace $ns"
     fi
 done
